/**
 * µGateway API (Public - Domain)
 * This document describes the Wiser-by-Feller `RESTful API` of the µGateway.
 *
 * The version of the OpenAPI document: 5.1.25
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * [read-only] output element
 */
export interface DeviceExtendedPropertiesOutputsInner {
  /**
   * [read-only] unique load id
   */
  load?: number;
  /**
   * Output Channel Main-Type [`onoff`, `dim`, `motor`, `dali`]
   */
  type?: string;
  /**
   * [read-only, default = `\"\"`] Output Channel Sub-Type
   */
  sub_type?: string;
}
