/**
 * µGateway API (Public - Domain)
 * This document describes the Wiser-by-Feller `RESTful API` of the µGateway.
 *
 * The version of the OpenAPI document: 5.1.25
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * [read-only] input element
 */
export interface DeviceExtendedPropertiesInputsInner {
  /**
   * [read-only] Input Channel Type [`up down`, `toggle`, `scene`]
   */
  type?: string;
}
